### ISSUE TITLE
Different naming for files

### ISSUE THREAD

**Issue by astiglic** [igorlogius/export-bookmarks-as-text#2]
**Is your feature request related to a problem? Please describe.**
In general I would advise never to start a filename with a number.
When there is multiple txt files generated, they might be mixed with some other temporary download files,
so it's best to have same starting name, which is obvious, so bookmarks is fine name.
Ideally it should have the name of the folder at the start.
For example if the folder is Music the file name could be:
bookmarks_Music_2023-05-09_10-27-17.txt
So if updated they will be next to each other in proper lineup.

Thanks.

**Comment by igorlogius** [comment]
While i dont really see a valid reason not to start a filename with a number ...i personally dont have an issue with changing the output format to something like `bookmarks_${BookmarkFolder}_YYYY-MM-DD_hh-mm-ss.txt`

notes: 

Since the download filename has the following browser built-in restrictions

1. no special characters allowed
2. filename length limit 

all special characters will need to be replaced with `_` underscores
and if necessary the bookarkfolder name parts will be truncated to not exceed the length limit.

**Comment by astiglic** [comment]
Regarding the start of the file name with number is because many tools can't read that file names properly, from the DOS time etc.
but also name conventions is important when working in big studios and this is one of the rules.
In this case maybe it wouldn't matter as much, but starting with bookmarks as a name is certainly better, since they will all be next to each other, easy to move, copy or just plain read and find the file ones need.
No special characters allowed is excellent, just like a filename length limit, so cool they are there as well.
Also it would be much easier to code let's say python script to read these bookmark files if named like that.
Regarding the name conventions, this is just first google explanation I found, but I hope I don't need to explain more then that.
https://gis.stackexchange.com/questions/7886/is-starting-names-with-numbers-a-bad-data-naming-convention

Thanks


-----Original Message-----

**Comment by astiglic** [comment]
Fantastic, thank you...
I tried everything to find the culprit for the other thing, but no luck so far...
Anyway, still it works in other profile which is great.
Thank you so much, this is excellent tool.


-----Original Message-----
